###########################
#                         #
# spring properties       #
#                         #
###########################
spring:
  integration:
    jdbc:
      initialize-schema: never
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
  application:
    name: odl-presp-revision-borrado-odl
  banner:
    location: classpath:santalucia-banner.txt
  mandatory-file-encoding: UTF-8
  cloud:
    task:
      initialize-enabled: false
      batch:
        fail-on-job-failure: true
      name: ${spring.application.name}
  security:
    oauth2:
      client:
        provider:
            presupuestoindividualodlcrud:
              issuer-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl
              jwk-set-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl/protocol/openid-connect/certs
            historicopresupuestoindividualodlcrud:
              issuer-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl
              jwk-set-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl/protocol/openid-connect/certs
            presupuestocolectivoodlcrud:
              issuer-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl
              jwk-set-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl/protocol/openid-connect/certs
            historicopresupuestocolectivoodlcrud:
              issuer-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl
              jwk-set-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl/protocol/openid-connect/certs
            declaracionesenlaodl:
              issuer-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl
              jwk-set-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl/protocol/openid-connect/certs
            historicodedeclaracionesenlaodlcrud:
              issuer-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl
              jwk-set-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl/protocol/openid-connect/certs
            objetosaseguradosodl:
              issuer-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl
              jwk-set-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl/protocol/openid-connect/certs
            historicoobjetoaseguradopresupuestoodlcrud:
              issuer-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl
              jwk-set-uri:
                https://sso-sldev.santalucia.es/auth/realms/stl-int-odl/protocol/openid-connect/certs
        registration:
            presupuestoindividualodlcrud:
              client-secret: 68014c21-d780-40b2-814c-21d780b0b211
              client-id: d461f8fe-55eb-11ee-ac10-cbbc50a070a5
              client-authentication-method: post
              authorization-grant-type: client_credentials
              scope: #scopes para la autorización
                - read:presupuesto-individual-odl
                - write:presupuesto-individual-odl
                - read-dynamic:presupuesto-individual-odl
            historicopresupuestoindividualodlcrud:
              client-secret: 68014c21-d780-40b2-814c-21d780b0b211
              client-id: d461f8fe-55eb-11ee-ac10-cbbc50a070a5
              client-authentication-method: post
              authorization-grant-type: client_credentials
              scope: #scopes para la autorización
                - read:historico-presupuesto-individual-odl
                - write:historico-presupuesto-individual-odl
                - read-dynamic:historico-presupuesto-individual-odl
            presupuestocolectivoodlcrud:
              client-secret: 68014c21-d780-40b2-814c-21d780b0b211
              client-id: d461f8fe-55eb-11ee-ac10-cbbc50a070a5
              client-authentication-method: post
              authorization-grant-type: client_credentials
              scope: #scopes para la autorización
                - read:presupuesto-colectivo-odl
                - write:presupuesto-colectivo-odl
                - read-dynamic:presupuesto-colectivo-odl
            historicopresupuestocolectivoodlcrud:
              client-secret: 68014c21-d780-40b2-814c-21d780b0b211
              client-id: d461f8fe-55eb-11ee-ac10-cbbc50a070a5
              client-authentication-method: post
              authorization-grant-type: client_credentials
              scope: #scopes para la autorización
                - read:historico-presupuesto-colectivo-odl
                - write:historico-presupuesto-colectivo-odl
                - read-dynamic:historico-presupuesto-colectivo-odl
            declaracionesenlaodl:
              client-secret: 68014c21-d780-40b2-814c-21d780b0b211
              client-id: d461f8fe-55eb-11ee-ac10-cbbc50a070a5
              client-authentication-method: post
              authorization-grant-type: client_credentials
              scope: #scopes para la autorización
                - read:declaraciones-odl
                - write:declaraciones-odl
                - read-dynamic:declaraciones-odl
            historicodedeclaracionesenlaodlcrud:
              client-secret: 68014c21-d780-40b2-814c-21d780b0b211
              client-id: d461f8fe-55eb-11ee-ac10-cbbc50a070a5
              client-authentication-method: post
              authorization-grant-type: client_credentials
              scope: #scopes para la autorización
                - read:historico-declaraciones-odl
                - write:historico-declaraciones-odl
                - read-dynamic:historico-declaraciones-odl
            objetosaseguradosodl:
              client-secret: 68014c21-d780-40b2-814c-21d780b0b211
              client-id: d461f8fe-55eb-11ee-ac10-cbbc50a070a5
              client-authentication-method: post
              authorization-grant-type: client_credentials
              scope: #scopes para la autorización
                - read:objeto-asegurado-presupuesto-odl
                - write:objeto-asegurado-presupuesto-odl
                - read-dynamic:objeto-asegurado-presupuesto-odl
            historicoobjetoaseguradopresupuestoodlcrud:
              client-secret: 68014c21-d780-40b2-814c-21d780b0b211
              client-id: d461f8fe-55eb-11ee-ac10-cbbc50a070a5
              client-authentication-method: post
              authorization-grant-type: client_credentials
              scope: #scopes para la autorización
                - read:historico-objeto-asegurado-presupuesto-odl
                - write:historico-objeto-asegurado-presupuesto-odl
                - read-dynamic:historico-objeto-asegurado-presupuesto-odl

  batch:
    jdbc:
      initialize-schema: never
      isolation-level-for-create: read-committed
  task:
    execution:
      pool:
        core-size: 10
        max-size: 10
        queue-capacity: 10

###########################
#                         #
# Batch Configuration     #
#                         #
###########################
santalucia:
  ams:
    features:
      retryers:
        definitions:
          recibos-reader:
            delay-expression: 1000
            max-delay-expression: 5000
            multiplier-expression: 2
            max-attempts-expression: 10
            retry-status-codes: 500,502,503,504
      feign:
        base-packages: com.santalucia

# Configurar caracteristicas propias de la aplicacion
app:
  custom:
    features:
      chunk-size: 1000
      cvs-path: ../../test/resources/data/csv/dummyFile.csv

###########################
#                         #
# micrometer properties   #
#                         #
###########################
management:
  metrics:
    tags:
      #Needed by micrometer +1.1.0
      application: ${spring.application.name}

###########################
#                         #
# info properties         #
#                         #
###########################
info:
  app:
    name: ${spring.application.name}
    encoding: UTF-8
    java:
      source: 17
      target: 17

###########################
#                         #
# logging properties      #
#                         #
###########################
logging:
  level:
    root: INFO
    "[com.santalucia]": DEBUG
    "[org.springframework]": INFO
---
#Profile habilitado de forma automatica cuando se despliega en OCP
spring:
  config:
    activate:
      on-profile:
        - kubernetes
  banner:
    location: classpath:santalucia-banner.json
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: false

